Repository bubkoo/html-to-image, pull requests merged in 2021-07, with the labels that each got.

#148 Fix srcset
  src/embedImages.ts
Labels: fix, needs-more-info

#146 feat: ✨ Add viewBox attribute to SVG
  src/createSvgDataURL.ts
  test/spec/index.spec.ts
Labels: feature, stale

#137 fix: Correct typo for word "default"
  README.md
Labels: needs-more-info, stale

#136 docs: update readme with react example
  README.md
Labels: chore
