Repository bubkoo/html-to-image, pull requests merged in 2022-08, with the labels that each got.

#280 fix: 🐛 selected option not preserved in image
  src/cloneNode.ts
Labels: stale, PR: unreviewed, fix

#270 fix: 🐛 text breaks on the last word
  src/cloneNode.ts
Labels: stale, PR: unreviewed

#297 fix: 🐛 cloneCSSStyle: copy transformOriginProp
  src/cloneNode.ts
Labels: stale, PR: unreviewed, fix

#260 feat: ✨ added includeQueryParams flag
  .eslintrc
  README.md
  src/embedWebFonts.ts
  src/getBlobFromURL.ts
  src/options.ts
Labels: stale, PR: unreviewed, feature

#308 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: needs-more-info, PR: unreviewed, size/L
