Repository bubkoo/html-to-image, pull requests merged in 2022-12, with the labels that each got.

#325 Fix Safari images
  README.md
  src/embed-images.ts
  src/util.ts
Labels: PR: unreviewed, fix

#343 feat: support webp format
  src/mimes.ts
  test/resources/webp/image.webp
  test/resources/webp/node.html
  test/resources/webp/style.css
  test/spec/basic.spec.ts
Labels: PR: unreviewed, size/S, PR(feature)

#344 fix: clone svg symbols
  src/clone-node.ts
  test/resources/svg-use-tag/image
  test/resources/svg-use-tag/node.html
  test/resources/svg-use-tag/style.css
  test/spec/svg.spec.ts
Labels: needs-more-info, PR: unreviewed, size/L, PR(fix)

#346 fix: use frames for video capture & add iframes
  src/clone-node.ts
Labels: PR: unreviewed
